CREATE DATABASE [RENTACAR] ON PRIMARY
( NAME = N'RENTACAR',
 FILENAME = N'C:\Users\xy\Desktop\BAZAMAHE\RENTACAR.mdf' ,
 SIZE = 4096KB ,
 MAXSIZE = UNLIMITED,
 FILEGROWTH = 10%)

LOG ON
( NAME = N'RENTACAR_log',
 FILENAME = N'C:\Users\xy\Desktop\BAZAMAHE\RENTACAR_log.LDF' ,
 SIZE = 2048KB ,
 MAXSIZE = UNLIMITED,
 FILEGROWTH = 10%)
