CREATE TABLE DBO.TBLAUTA (
AUTAID INT NOT NULL PRIMARY KEY IDENTITY,
MARKA NVARCHAR(20) NOT NULL,
GODISTE VARCHAR(20) NOT NULL,
VRSTAGORIVA NVARCHAR(20) NOT NULL,
KORISNIK INT NOT NULL,
GRAD   INT NOT NULL,
KANTON INT NOT NULL,
BANKA INT NOT NULL,
);
