CREATE TABLE DBO.TBLAUTA (
AUTAID INT NOT NULL PRIMARY KEY IDENTITY,
MARKA NVARCHAR(20) NOT NULL,
GODISTE VARCHAR(20) NOT NULL,
VRSTAGORIVA NVARCHAR(20) NOT NULL,
KORISNIKID INT NOT NULL,
GRADID   INT NOT NULL,
KANTONID INT NOT NULL,
BANKAID INT NOT NULL,
);
